version: '3.8'
services:
  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_DB=HwRemind
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "6000:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: RevokedTokens_Cache
    image: redis
    ports:
      - "7000:6379"